### ISSUE TITLE
将k-style转为 css文件，按职责属性分为多份文件

### ISSUE THREAD

**Issue by kuyoru-kamikisho** [kuyoru-kamikisho/kcvex#8]
```css
/** ---------------------------------------------------------------------------------*
 ** 字体
 ** ---------------------------------------------------------------------------------*/
.text-white {
    color: white;
}

.text-black {
    color: black;
}

.text-nowrap {
    white-space: nowrap;
}

.text-break {
    white-space: break-spaces;
}

.text-ellipsis {
    text-overflow: ellipsis;
}

.text-w600 {
    font-weight: 600;
}

.text-w500 {
    font-weight: 500;
}

.text-w400 {
    font-weight: 400;
}

.text-14 {
    font-size: 14px;
}

.text-16 {
    font-size: 16px;
}

.text-18 {
    font-size: 18px;
}

.text-20 {
    font-size: 20px;
}

.text-22 {
    font-size: 22px;
}

.text-24 {
    font-size: 24px;
}

.text-26 {
    font-size: 26px;
}

.text-28 {
    font-size: 28px;
}

.text-30 {
    font-size: 30px;
}

.text-32 {
    font-size: 32px;
}

/** ---------------------------------------------------------------------------------*
 ** 通用一般样式
 ** ---------------------------------------------------------------------------------*/

.w-100 {
    width: 100%;
}

.h-100 {
    height: 100%;
}

.flex-col {
    flex-direction: column;
}

.flex-col-reverse {
    flex-direction: column-reverse;
}

.flex-row {
    flex-direction: row;
}

.flex-row-reverse {
    flex-direction: row-reverse;
}

.flex-wrap {
    flex-wrap: wrap;
}

.flex-nowrap {
    flex-wrap: nowrap;
}

.position-absolute {
    position: absolute;
}

.position-relative {
    position: relative;
}

.k-locale-ltr {
    direction: ltr;
}

.k-locale-rtl {
    direction: rtl;
}

.d-flex {
    display: flex;
}

.d-grid {
    display: grid;
}

.d-contents {
    display: contents;
}

.d-inline-grid {
    display: inline-grid;
}

.d-block {
    display: block;
}

.d-inline-block {
    display: inline-block;
}

.box-sizing-border {
    box-sizing: border-box;
}

.box-sizing-content {
    box-sizing: content-box;
}

.selectable {
    user-select: auto;
}

.inselectable {
    user-select: none;
}

.justify-sb {
    justify-content: space-between;
}

.justify-ed {
    justify-content: end;
}

.justify-st {
    justify-content: start;
}

.justify-ct {
    justify-content: center;
}

.justify-rt {
    justify-content: right;
}

.justify-ar {
    justify-content: space-around;
}

.justify-ev {
    justify-content: space-evenly;
}

.align-ct {
    align-items: center;
}

.align-ed {
    align-items: end;
}

.align-st {
    align-items: start;
}

.flex-grow-1 {
    flex-grow: 1;
}

.round-16 {
    border-radius: 16px;
}

.round-14 {
    border-radius: 14px;
}

.round-12 {
    border-radius: 12px;
}

.round-10 {
    border-radius: 10px;
}

.round-8 {
    border-radius: 8px;
}

.round-6 {
    border-radius: 6px;
}

.round-4 {
    border-radius: 4px;
}

.round-2 {
    border-radius: 2px;
}

/**----------------------------------------------------------------------------------------
 *  渐变过渡
 * ----------------------------------------------------------------------------------------*/
.kfade-enter-active, .kfade-leave-active {
    transition: opacity .2s;
}

.kfade-enter, .kfade-leave-to,
.kfade-enter-from {
    opacity: 0;
}

/**----------------------------------------------------------------------------------------
 *  海拔
 * ----------------------------------------------------------------------------------------*/
.elevation-0 {
    box-shadow: 0 0 0 0 rgba(0, 0, 0, .2), 0 0 0 0 rgba(0, 0, 0, .14), 0 0 0 0 rgba(0, 0, 0, .12);
}

.elevation-1 {
    box-shadow: 0 2px 1px -1px rgba(0, 0, 0, .2), 0 1px 1px 0 rgba(0, 0, 0, .14), 0 1px 3px 0 rgba(0, 0, 0, .12);
}

.elevation-2 {
    box-shadow: 0 3px 1px -2px rgba(0, 0, 0, .2), 0 2px 2px 0 rgba(0, 0, 0, .14), 0 1px 5px 0 rgba(0, 0, 0, .12);
}

.elevation-3 {
    box-shadow: 0 3px 3px -2px rgba(0, 0, 0, .2), 0 3px 4px 0 rgba(0, 0, 0, .14), 0 1px 8px 0 rgba(0, 0, 0, .12);
}

.elevation-4 {
    box-shadow: 0 2px 4px -1px rgba(0, 0, 0, .2), 0 4px 5px 0 rgba(0, 0, 0, .14), 0 1px 10px 0 rgba(0, 0, 0, .12);
}

.elevation-5 {
    box-shadow: 0 3px 5px -1px rgba(0, 0, 0, .2), 0 5px 8px 0 rgba(0, 0, 0, .14), 0 1px 14px 0 rgba(0, 0, 0, .12);
}

.elevation-6 {
    box-shadow: 0 3px 5px -1px rgba(0, 0, 0, .2), 0 6px 10px 0 rgba(0, 0, 0, .14), 0 1px 18px 0 rgba(0, 0, 0, .12);
}

.elevation-7 {
    box-shadow: 0 4px 5px -2px rgba(0, 0, 0, .2), 0 7px 10px 1px rgba(0, 0, 0, .14), 0 2px 16px 1px rgba(0, 0, 0, .12);
}

.elevation-8 {
    box-shadow: 0 5px 5px -3px rgba(0, 0, 0, .2), 0 8px 10px 1px rgba(0, 0, 0, .14), 0 3px 14px 2px rgba(0, 0, 0, .12);
}

.elevation-9 {
    box-shadow: 0 5px 6px -3px rgba(0, 0, 0, .2), 0 9px 12px 1px rgba(0, 0, 0, .14), 0 3px 16px 2px rgba(0, 0, 0, .12);
}

.elevation-10 {
    box-shadow: 0 6px 6px -3px rgba(0, 0, 0, .2), 0 10px 14px 1px rgba(0, 0, 0, .14), 0 4px 18px 3px rgba(0, 0, 0, .12);
}

.elevation-11 {
    box-shadow: 0 6px 7px -4px rgba(0, 0, 0, .2), 0 11px 15px 1px rgba(0, 0, 0, .14), 0 4px 20px 3px rgba(0, 0, 0, .12);
}

.elevation-12 {
    box-shadow: 0 7px 8px -4px rgba(0, 0, 0, .2), 0 12px 17px 2px rgba(0, 0, 0, .14), 0 5px 22px 4px rgba(0, 0, 0, .12);
}

.elevation-13 {
    box-shadow: 0 7px 8px -4px rgba(0, 0, 0, .2), 0 13px 19px 2px rgba(0, 0, 0, .14), 0 5px 24px 4px rgba(0, 0, 0, .12);
}

.elevation-14 {
    box-shadow: 0 7px 9px -4px rgba(0, 0, 0, .2), 0 14px 21px 2px rgba(0, 0, 0, .14), 0 5px 26px 4px rgba(0, 0, 0, .12);
}

.elevation-15 {
    box-shadow: 0 8px 9px -5px rgba(0, 0, 0, .2), 0 15px 22px 2px rgba(0, 0, 0, .14), 0 6px 28px 5px rgba(0, 0, 0, .12);
}

.elevation-16 {
    box-shadow: 0 8px 10px -5px rgba(0, 0, 0, .2), 0 16px 24px 2px rgba(0, 0, 0, .14), 0 6px 30px 5px rgba(0, 0, 0, .12);
}

.elevation-17 {
    box-shadow: 0 8px 11px -5px rgba(0, 0, 0, .2), 0 17px 26px 2px rgba(0, 0, 0, .14), 0 6px 32px 5px rgba(0, 0, 0, .12);
}

.elevation-18 {
    box-shadow: 0 9px 11px -5px rgba(0, 0, 0, .2), 0 18px 28px 2px rgba(0, 0, 0, .14), 0 7px 34px 6px rgba(0, 0, 0, .12);
}

.elevation-19 {
    box-shadow: 0 9px 12px -6px rgba(0, 0, 0, .2), 0 19px 29px 2px rgba(0, 0, 0, .14), 0 7px 36px 6px rgba(0, 0, 0, .12);
}

.elevation-20 {
    box-shadow: 0 10px 13px -6px rgba(0, 0, 0, .2), 0 20px 31px 3px rgba(0, 0, 0, .14), 0 8px 38px 7px rgba(0, 0, 0, .12);
}

.elevation-21 {
    box-shadow: 0 10px 13px -6px rgba(0, 0, 0, .2), 0 21px 33px 3px rgba(0, 0, 0, .14), 0 8px 40px 7px rgba(0, 0, 0, .12);
}

.elevation-22 {
    box-shadow: 0 10px 14px -6px rgba(0, 0, 0, .2), 0 22px 35px 3px rgba(0, 0, 0, .14), 0 8px 42px 7px rgba(0, 0, 0, .12);
}

.elevation-23 {
    box-shadow: 0 11px 14px -7px rgba(0, 0, 0, .2), 0 23px 36px 3px rgba(0, 0, 0, .14), 0 9px 44px 8px rgba(0, 0, 0, .12);
}

.elevation-24 {
    box-shadow: 0 11px 15px -7px rgba(0, 0, 0, .2), 0 24px 38px 3px rgba(0, 0, 0, .14), 0 9px 46px 8px rgba(0, 0, 0, .12);
}
```
